return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    -- lazy = 0,
    main = "nvim-treesitter.configs",
    opts = {
      ensure_installed = {
        "bash",
        "c",
        "diff",
        "dockerfile",
        "gitignore",
        "go",
        "graphql",
        "haskell",
        "html",
        "javascript",
        "jsdoc",
        "json",
        "jsonc",
        "lua",
        "luadoc",
        "luap",
        "markdown",
        "markdown_inline",
        "printf",
        "python",
        "query",
        "regex",
        "rust",
        "scss",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
      },
        sync_install = true,
        highlight = { enable = true },
        indent = { enable = true },  
    },
  },
}
